# -*- coding: utf-8 -*-
"""IT21044472 ISP Project V1.4 final code base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Yezc964yCN2zlHYiPwQ0fmJjpLJQ9Zw
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

from google.colab import drive
drive.mount('/content/drive')

# Load your dataset
data = pd.read_csv('/content/drive/MyDrive/YEAR3/SEM 2/ISP/web server access logs.csv',header=0)

# Ensure 'is_anomaly' is in integer format (0 or 1)
label_encoder = LabelEncoder()
data['is_anomaly'] = label_encoder.fit_transform(data['is_anomaly'])

# Use only 'status_code' as the feature
X = data[['status_code']]
y = data['is_anomaly']

# Create and train the Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

input_data = pd.DataFrame({'status_code': [300]})
predicted_anomaly = model.predict(input_data)
if predicted_anomaly[0] == 1:
    output_message = "This log is suspicious"
else:
    output_message = "This log is not suspicious"

print(output_message)

